import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Layout } from '@/components/layout';
import { getCookie } from '@/helper/cookiesHander';
import { LoginForm } from '@/components/login-form';
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getCookie('token');

  return <>{token ? <Layout>{children}</Layout> : <LoginForm />}</>;
}
