import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Layout } from '@/components/layout';
import { getCookie } from '@/helper/cookies-hander';
import { LoginForm } from '@/components/login-form';
import MyProvider from '@/redux/my-provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getCookie('token');
  return (
    <>
      {token ? (
        <MyProvider>
          <Layout>{children}</Layout>
        </MyProvider>
      ) : (
        <LoginForm />
      )}
    </>
  );
}
